name: Test

on: [workflow_dispatch]

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Prepares database
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: '8.0'
      - run: >
          mysql -uroot -h127.0.0.1 << "EOF"
            CREATE DATABASE IF NOT EXISTS users_test;
            USE users_test;
            DROP TABLE IF EXISTS `users`;
            CREATE TABLE `users` (
              `uuid` varchar(191) NOT NULL,
              `created_at` datetime(3) DEFAULT NULL,
              `deleted_at` datetime(3) DEFAULT NULL,
              `first_name` varchar(255) DEFAULT NULL,
              `phone` varchar(255) DEFAULT NULL,
              PRIMARY KEY (`uuid`)
            );

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Run tests
        run: DB_USER_TEST=root DB_HOSTNAME_TEST=127.0.0.1 DB_PORT_TEST=3306 DB_SCHEMA_TEST=users_test go test
